= Esmond Tan  - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:

== Overview

This portfolio aims to document my contributions as a developer to the Inventory Manager project. In addition, it
showcases my ability to work in a development team using an advanced collaboration tool, GitHub. It also exhibits
my ability to manage a project for a team.

Inventory Manager was developed for Small to Medium Enterprises (SMEs) to tackle the
chore of stock taking. Designed to be easy to use, Inventory Manager gives the user control over
their business right from their keyboard.

Inventory Manager comes with features to manage the shop inventory such as creating sale orders,
purchase orders, generating reports and more. With user authentication built in,
it gives SMEs greater control over users' access to the application too.


== Summary of contributions

|===
|_Below is a summary of the contributions I have made to the project._
|===

* *Major Enhancement*: Developed Sale Orders Management Feature

** What it does: This feature allows the user to create a sale order in the application. When a sale order is created, Inventory Manager will automatically deduct stocks from the inventory.

** Justification: This feature is critical for Inventory Manager to work. Without the ability to create sale orders, Inventory Manager will not be able to track and manage item stocks accurately.

** Highlights: This feature requires interaction with the update item command in Inventory Manager and the ability to validate item quantity before a sale is allowed.

* *Minor Enhancement*: Added support for undo / redo on sale orders

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=esmondtan[Reposense]]

* *Other contributions*:

** Project Management:

*** Managed release `v1.2.2` on GitHub [https://github.com/CS2103-AY1819S1-W14-4/main/releases/tag/v1.2.2[GitHub]]

** Documentation:

*** Updated the introduction of the User Guide (Pull requests https://github.com/CS2103-AY1819S1-W14-4/main/pull/93[#93])
*** Added the section on Sale Orders Management to the User Guide (Pull requests https://github.com/CS2103-AY1819S1-W14-4/main/pull/93[#93])
*** Updated various sections of the Developer Guide (Pull requests https://github.com/CS2103-AY1819S1-W14-4/main/pull/93[#93])
*** Added the section on Sale Order Creation to the Developer Guide (Pull requests https://github.com/CS2103-AY1819S1-W14-4/main/pull/93[#93])

** Community:

*** Reviewed Pull Requests [https://github.com/CS2103-AY1819S1-W14-4/main/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3AEsmondTan[GitHub]]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=salesManagement]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=saleOrderCreation]
