= Yao TengXiong  - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

:sectnums:

== Overview

This portfolio represents my work as a software engineer and developer for the Inventory Manager project.
It contains and documents my contributions to the project, and demonstrates my ability to work with others in a team.
On top of that, it aims to showcase my ability as a competent developer equipped with the necessary skills in project management.

The Inventory Manager project aims to address the inventory management issues that Small to Medium Enterprises (SMEs) encounter
in their daily business operations. It is managed and developed by a team of five members who worked closely together for
more than three months on this project.

The Inventory Manager is a desktop inventory management application that has to be interacted with using Command-Line
Interface (CLI) with a keyboard. It allows verified users to perform varying inventory management tasks such as filtering items,
checking items on low stock, generating reports, creating purchase orders and many more.

== Summary of Contributions

* *Major enhancement*: Added the *Inventory Management* feature
*** *What it does*: It allows verified users to add/edit/delete items in the inventory list. It also provides various inventory
management tools, such as searching for items, checking for items that are low on stock and filtering of items.
*** *Justification*: This feature is the core of the Inventory Manager as it allows for proper stock control and management
of the inventory without the need for manual recording of stock.
*** *Highlight*: Only verified users such as the administrator, manager and staff are allowed to perform inventory management related tasks.

* *Minor enhancement*:
*** Added image support for items
*** Display warning for items that are low on stock
*** Modified existing browser panel to display item information

* *Code contributed*: [https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=yao-tx[Reposense]]

* *Other contributions*:

** Project management:
*** Transformed and modified the Address Book into the current Inventory Manager
*** Managed release `v1.2.1` on GitHub [https://github.com/CS2103-AY1819S1-W14-4/main/releases/tag/1.2.1[Release 1.2.1]]

** Documentation:
*** Added, formatted and improved the Inventory Management and Design sections of the Developer Guide
*** Performed cosmetic tweaks and improved existing contents of the User Guide

** Community:
*** Reviewed and commented on Pull Requests made by teammates [https://github.com/CS2103-AY1819S1-W14-4/main/pulls?q=is%3Apr+reviewed-by%3Ayao-tx+is%3Aclosed[GitHub]]
*** Tested and reviewed Team T12-3's project and gave comments on issues

== Contributions to the User Guide


|===
|_Given below are some of the sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=pppInventoryManagement1]
include::../UserGuide.adoc[tag=pppInventoryManagement2]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=pppInventoryManagement]

---

