= Yao TengXiong  - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Inventory Manager

---

== Overview

Inventory Manager is a desktop inventory management application designed specifically for Small to Medium Enterprises(SMEs) to manage their inventories.
It allows users to perform multiple inventory management tasks such as creating sales, genearting reports, reating purchase orders and more.
The

Inventory manager is a desktop application designed for Small to Medium Enterprises (SMEs) to manage their shop inventory. It allows users to perform multiple inventory management tasks such as creating sales, generating reports, creating purchase orders and more.

The main purpose of the application is to provide good inventory control for SMEs so that they are able to run an efficient business and make money in the process.

More importantly, it is optimized for those who prefer to work with a Command Line Interface (CLI) while still having the benefits of a Graphical User Interface (GUI).

Ensure inventory control for your company now by jumping to Section 3, “Quick Start”. Enjoy!

Inventory Manager is a desktop inventory management application designed specially for Small to Medium Enterprises (SMEs). The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Inventory Management of the Inventory Manager App

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]]

* *Other contributions*:

** Minor Enhancements:
*** Add/Delete/Edit items in inventory
*** Export/Import of Inventories through .csv
*** Image support for items
*** Develop inventory management API

** Project Management:
*** In charge of transforming and modifying the Address Book into the current Inventory Manager

** Others:
*** Storage

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
***
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
** Tools:
*** Created an organization for team on Github
*** Integrated a Github plugin (TravisCI) to the team repo

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]

---

