= Muhd Zulqarnain  - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:sectnums:

== Overview

Hello! My name is Zul and I'm a student at National University of Singapore (NUS). My future hope is to be a good developer.
To start off my software developer path, I have developed a desktop application called Inventory Manager as part of an NUS Software Engineering module project.
This portfolio provides you with information about various contributions that I have done for the project. This project is a small sample of the multiple talents
that I have that will contribute to my future employment.

Inventory Manager is an inventory management solution aims to tackle the chore of stock taking for Small to Medium Enterprises (SMEs). Designed to be easy
to use, Inventory Manager gives the users control over their business right from their keyboard.

Inventory Manager also allows users to perform multiple inventory management tasks such as creating sales, generating reports, creating purchase orders and more.
With user authentication put in place, it gives SMEs greater control over users' access to the application as well.

== Summary of Contributions

* *Major Enhancement*: Added the *Purchase Orders Management* Feature

** What it does: Allows the user to generate purchase order in the application.
When a purchase order is approved by the manager, Inventory Manager will automatically update the stocks in the inventory.

** Justification: This feature *allows user to restock item easily and manage the purchase order details efficiently*.
It also tackles the issue of the hassle of writing hard-copy purchase orders.

** Highlights: This feature is dependant of the item storage as purchase order can only be created on existing items.
It is also tied with user management as only manager can approve/reject a purchase order.
Deleting and editing an item must now update the relevant purchase orders as well.

* *Minor Enhancement*: Rearranged the command box to the bottom of the Inventory Manager User Interface
** Justification: Provides a more user friendly visual for the user.
* *Other Contributions*:

** Project Management:
*** Maintained issue tracker, milestone, pull request approval and merger.
*** Managed release `V1.3` on GitHub.

** Documentation:

*** Updated the user guides of Purchase Order Management component in Inventory Manager (Pull request https://github.com/CS2103-AY1819S1-W14-4/main/pull/150[#150])
*** Updated the developer guides of Purchase Order Management component in Inventory Manager (Pull request https://github.com/CS2103-AY1819S1-W14-4/main/pull/150[#150])
*** Updated the team's about us page (Pull request https://github.com/CS2103-AY1819S1-W14-4/main/pull/150[#150])
*** Updated the storage and Ui class diagram in develop guide (Pull request https://github.com/CS2103-AY1819S1-W14-4/main/pull/208[#208])



** Community:

*** Reviewed project done by other group and suggested improvements based on the bugs found. (W17-1 Issue https://github.com/CS2103-AY1819S1-W17-1/main/issues/249)[#249])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=purchaseOrderManagement]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=purchaseOrderManagement]

---
